feat: ae2 empty interface compatibility (item + fluids) and some other refactoring
TeamDman/SuperFactoryManager pull request #193
Opened 2024-11-11 10:09 UTC by Vonr

2024-11-13 21:19 UTC, TeamDman requested changes

2024-11-13 21:19 UTC, TeamDman commented on src/main/java/ca/teamdman/sfm/common/capabilityprovidermapper/ae2/InterfaceCapabilityProviderMapper.java
> +    private static InterfaceBlockEntity interfaceAt(LevelAccessor level, BlockPos pos) {
```suggestion
    private static @Nullable InterfaceBlockEntity interfaceAt(LevelAccessor level, BlockPos pos) {
```

2024-11-13 21:19 UTC, TeamDman commented on src/main/java/ca/teamdman/sfm/common/capabilityprovidermapper/ae2/InterfaceCapabilityProviderMapper.java
> +        InterfaceBlockEntity getInterface() {
```suggestion
        @Nullable InterfaceBlockEntity getInterface() {
```

2024-11-13 21:19 UTC, TeamDman commented on src/main/java/ca/teamdman/sfm/common/capabilityprovidermapper/ae2/InterfaceCapabilityProviderMapper.java
> +        IEnergyService getEnergy() {
```suggestion
        @Nullable IEnergyService getEnergy() {
```

2024-11-13 21:19 UTC, TeamDman commented on src/main/java/ca/teamdman/sfm/common/capabilityprovidermapper/ae2/InterfaceCapabilityProviderMapper.java
> +        LazyOptional<IStorageMonitorableAccessor> getCapability() {
```suggestion
        LazyOptional<IStorageMonitorableAccessor> getCapability() {
```
the package file should be adding notnullbydefault to everything

2024-11-13 21:19 UTC, TeamDman commented on src/main/java/ca/teamdman/sfm/common/capabilityprovidermapper/ae2/InterfaceCapabilityProviderMapper.java
> +        public @NotNull ItemStack getStackInSlot(int slot) {
```suggestion
        public ItemStack getStackInSlot(int slot) {
```
the package file should be adding notnullbydefault to everything

2024-11-13 21:19 UTC, TeamDman commented on src/main/java/ca/teamdman/sfm/common/capabilityprovidermapper/ae2/InterfaceCapabilityProviderMapper.java
> +        public @NotNull ItemStack insertItem(int slot, @NotNull ItemStack stack, boolean simulate) {
```suggestion
        public ItemStack insertItem(int slot, @NotNull ItemStack stack, boolean simulate) {
```
the package file should be adding notnullbydefault to everything

2024-11-13 21:19 UTC, TeamDman commented on src/main/java/ca/teamdman/sfm/common/capabilityprovidermapper/ae2/InterfaceCapabilityProviderMapper.java
> +        public @NotNull ItemStack extractItem(int slot, int amount, boolean simulate) {
```suggestion
        public ItemStack extractItem(int slot, int amount, boolean simulate) {
```
the package file should be adding notnullbydefault to everything

2024-11-13 21:19 UTC, TeamDman commented on src/main/java/ca/teamdman/sfm/common/capabilityprovidermapper/ae2/InterfaceCapabilityProviderMapper.java
> +        public @NotNull FluidStack getFluidInTank(int tank) {
```suggestion
        public FluidStack getFluidInTank(int tank) {
```

2024-11-13 21:19 UTC, TeamDman commented on src/main/java/ca/teamdman/sfm/common/capabilityprovidermapper/ae2/InterfaceCapabilityProviderMapper.java
> +        public @NotNull FluidStack drain(FluidStack resource, FluidAction action) {
```suggestion
        public FluidStack drain(FluidStack resource, FluidAction action) {
```

2024-11-13 21:19 UTC, TeamDman commented on src/main/java/ca/teamdman/sfm/common/capabilityprovidermapper/ae2/InterfaceCapabilityProviderMapper.java
> +        public @NotNull FluidStack drain(int maxDrain, FluidAction action) {
```suggestion
        public FluidStack drain(int maxDrain, FluidAction action) {
```

2024-11-13 21:19 UTC, TeamDman commented on src/main/java/ca/teamdman/sfm/common/compat/SFMCompat.java
>      }
why are we returning a new array here?
`if (!empty) return it; else fill it and return it`
no need for set here

2024-11-13 21:19 UTC, TeamDman commented on src/main/java/ca/teamdman/sfm/common/compat/SFMCompatGatherCapabilitiesEvent.java
don't think this is necessary

any block that wants SFM compatibility should implement the IItemHandler/etc caps like normal

2024-11-13 21:19 UTC, TeamDman commented on src/main/java/ca/teamdman/sfm/common/compat/SFMMekanismCompat.java
> +@Mod.EventBusSubscriber
why

2024-11-14 10:29 UTC, Vonr commented on src/main/java/ca/teamdman/sfm/common/compat/SFMCompat.java
>      }
returning the existing array is giving a mutable reference to it.

2024-11-14 10:30 UTC, Vonr commented on src/main/java/ca/teamdman/sfm/common/compat/SFMMekanismCompat.java
> +@Mod.EventBusSubscriber
oops, artifact from converting the mekanism compat to use the event

2024-11-14 10:31 UTC, Vonr commented on src/main/java/ca/teamdman/sfm/common/compat/SFMCompatGatherCapabilitiesEvent.java
fair enough

2024-11-20 00:32 UTC, TeamDman approved these changes

2024-11-20 00:51 UTC, merged